### ISSUE TITLE
Incompatibilidad con 3.40.0

### ISSUE THREAD

**Issue by pablohevia** [fpsampayo/zoomrc#10]
Hola @fpsampayo

En QGIS 3.40.0, al abrir, da este error:

> 2024-11-08T12:09:41     CRITICAL    Traceback (most recent call last):
>               File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
>               plugins[packageName] = package.classFactory(iface)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>               File "C:\Users/Pablo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\__init__.py", line 35, in classFactory
>               from .zoomrc import ZoomRC
>               File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 966, in _import
>               mod = _builtin_import(name, globals, locals, fromlist, level)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>               File "C:\Users/Pablo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\zoomrc.py", line 29, in 
>               from .gui.zoomrc_dockwidget import ZoomRCDockWidget
>               File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 966, in _import
>               mod = _builtin_import(name, globals, locals, fromlist, level)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>               File "C:\Users/Pablo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\gui\zoomrc_dockwidget.py", line 32, in 
>               from zoomrc.core.catastroTools import CatastroTools
>               File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 966, in _import
>               mod = _builtin_import(name, globals, locals, fromlist, level)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>               File "C:\Users/Pablo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\core\catastroTools.py", line 27, in 
>               from qgis.gui import QgsRubberBand, Qgis
>              ImportError: cannot import name 'Qgis' from 'qgis.gui' (C:\OSGeo4W/apps/qgis/./python\qgis\gui\__init__.py). Did you mean: 'qgis'?

Quizá haya una solución más limpia, pero lo he resuelto con la ayuda de ChatGPT, editando catastroTools.py y he dejado así los import del principio:
```
from urllib import request, parse
from xml.dom import minidom
from qgis.core import QgsVectorLayer, QgsRectangle, QgsProject
from qgis.gui import QgsRubberBand
from PyQt5.QtGui import QColor

# Importación condicional de Qgis para compatibilidad con varias versiones
try:
    from qgis.core import Qgis  # Intentar importar desde qgis.core (para versiones más nuevas)
except ImportError:
    from qgis.gui import Qgis  # En caso de error, importar desde qgis.gui (para versiones anteriores)
```

**Comment by cneirac** [comment]
En QGis 3.20 Odense para Windows instálase con erro, non aparece o botón/barra de ferramentas e non funciona:

Non se pode cargar o plugin 'zoomrc' debido a un erro chamando ó seu método classFactory() 

ImportError: cannot import name 'Qgis' from 'qgis.gui' (C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\gui\__init__.py) 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\__init__.py", line 35, in classFactory
    from .zoomrc import ZoomRC
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\zoomrc.py", line 29, in 
    from .gui.zoomrc_dockwidget import ZoomRCDockWidget
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\gui\zoomrc_dockwidget.py", line 32, in 
    from zoomrc.core.catastroTools import CatastroTools
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\core\catastroTools.py", line 27, in 
    from qgis.gui import QgsRubberBand, Qgis
ImportError: cannot import name 'Qgis' from 'qgis.gui' (C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\gui\__init__.py)


Versión Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versión QGIS: 3.20.0-Odense Odense, decaadbb31 

Ruta Python:
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.20.0\bin\python39.zip
C:\PROGRA~1\QGIS32~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.20.0\bin
C:\PROGRA~1\QGIS32~1.0\apps\Python39
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
D:\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc
.
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\XYZHubConnector\external

**Comment by fpsampayo** [comment]
Hola!

He publicado nueva versión 0.6.3 y ya está disponible en plugins.qgis.org por lo que podéis probar a instalarla desde qgis.

Os dejo por aquí la PR que tiene más descripción: https://github.com/fpsampayo/zoomrc/pull/13

@cneirac He probado desde qgis 3.36 hasta 3.44, seguramente en 3.20 te funcione también, pero sino, siendo tan antigua, igual es mejor que pienses en actualizar.

Si os funciona bien, avisad, y cerramos esta issue.

**Comment by cneirac** [comment]
Gracias @fpsampayo funcionando correctamente en 3.20

**Comment by fpsampayo** [comment]
Me alegro, cierro issue.
