### ISSUE TITLE
Complemento no funciona en Qgis 3.30

### ISSUE THREAD

**Issue by josotero** [fpsampayo/zoomrc#7]
¿Hay alguna solución para que el complemento funcione en la versión 3.30?

Muchas gracias por el aporte, es un complemento realmente útil.

**Comment by jfcamach1973** [comment]
Yo tambien estoy buscandole solución. Desde que instalé la nueva versión, me da error de python


2023-06-30T11:01:09     WARNING    Traceback (most recent call last):
              File "C:\Users/jfcamach.HUERCAL-OVERA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\zoomrc.py", line 224, in run
              self.dockwidget = ZoomRCDockWidget(iface = self.iface)
              File "C:\Users/jfcamach.HUERCAL-OVERA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\gui\zoomrc_dockwidget.py", line 67, in __init__
              self.catastroTools = CatastroTools(iface)
              File "C:\Users/jfcamach.HUERCAL-OVERA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zoomrc\core\catastroTools.py", line 38, in __init__
              self.rubber = QgsRubberBand(self.iface.mapCanvas(), True)
             TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

**Comment by jfcamach1973** [comment]
Y es un complemento de mucha utilidad

**Comment by fpsampayo** [comment]
perdón pero no lo estoy usando y qgis poco y ni me enteré.

A ver si aún os ayuda.

**Comment by pablohevia** [comment]
Lo acabo de probar en QGIS 3.36.3 y vuelve a ir de cine. Gracias, @fpsampayo

**Comment by tizzenn** [comment]
Para mi, en el cambio a 3.28.12-Firenze se rompe el plugin.
